services:
  frontend:
    container_name: frontend_manutencao
    build:
      context: ./manutencao-e-evolucao/
    ports:
      - 80:3000

  backend:
    container_name: backend_manutencao
    build:
      context: ./server/
    ports:
      - 4466:8080
    depends_on:
      db_manutencao:
        condition: service_healthy

  db_manutencao:
    container_name: db_manutencao
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mes_db
      - MYSQL_ROOT_PASSWORD=banco123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  phpmyadmin:
    container_name: db_manutencao_gui
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db_manutencao
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=banco123
    depends_on:
      - db_manutencao
volumes:
  mysql_data:
  mysql_config:
